export const REQ_PROD_LIST = 'REQ_PROD_LIST';
export const SUCCESS_PROD_LIST = 'SUCCESS_PROD_LIST';
export const FAIL_PROD_LIST = 'PFAIL_PROD_LIST';

export const REQ_PROD_DETAL = 'REQ_PROD_DETAL';
export const SUCCESS_PROD_DETAL = 'SUCCESS_PROD_DETAL';
export const FAIL_PROD_DETAL = 'FAIL_PROD_DETAL';

export const FAIL_PROD_UPLOAD = 'FAIL_PROD_UPLOAD';
export const REQ_PROD_UPLOAD = 'REQ_PROD_UPLOAD';
export const SUCCESS_PROD_UPLOAD = 'SUCCESS_PROD_UPLOAD';

export const REQ_PROD_DELE = 'REQ_PROD_DELE';
export const SUCCESS_PROD_DELE = 'SUCCESS_PROD_DELE';
export const FAIL_PROD_DELE = 'FAIL_PROD_DELE';
export const RESET_PROD_DELE = 'RESET_PROD_DELE';